Kancelaria365.Web/Controllers/KontaktController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SP = Microsoft.SharePoint.Client;
using System.Linq.Dynamic;
using System.Web;
using System.IO;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Configuration;
using Microsoft.IdentityModel.Claims;
using Microsoft.Identity.Client;
using Beta = GraphBeta;
using Kancelaria365.Data;
using Kancelaria365.Common;
using Kancelaria365.ConnectedServices;
using Kancelaria365.Common.Helpers;
using NLog;

namespace Kancelaria365.Web.Controllers
{
    public class KontaktController :
        BaseCacheGenericController<KontaktRepository, Kontakt>
    {
        private new static Logger logger = LogManager.GetCurrentClassLogger();

        [SharePointContextFilter]
        public ActionResult Index()
        {
            KontaktListViewModel model = null;
            using (Context)
            {
                model = new KontaktListViewModel(Context);
            }
            return View(model);
        }

        [SharePointContextFilter]
        public async Task<ActionResult> Details(int id)
        {
            KontaktViewModel viewModel = null;
            using (Context)
            {
                Kontakt kontaktEntity = KontaktRepository.GetEntityById(id);
                viewModel = new KontaktViewModel(this.HttpContext, Context, kontaktEntity, FormMode.Dispaly);
                await viewModel.Init();
            }
            return View("Edit", viewModel);
        }

        [SharePointContextFilter]
        public async Task<ActionResult> Create()
        {
            KontaktViewModel viewModel = null;

            using (Context)
            {
                viewModel = new KontaktViewModel(this.HttpContext, Context, FormMode.New);
                await viewModel.Init();
            }
            return View("Edit", viewModel);
        }

        [HttpPost]
        [SharePointContextFilter]
        public async Task<ActionResult> Create(KontaktViewModel viewModel, FormCollection collection)
        {
            using (Context)
            {
                viewModel = new KontaktViewModel(this.HttpContext, Context, viewModel.Kontakt, FormMode.New);
                await viewModel.Init(this.HttpContext);

                Beta.OrgContact contact = viewModel.KontaktyOrganizacji.FirstOrDefault(x => x.Id == viewModel.Kontakt.OutlookContact.Id);
                viewModel.Kontakt.OutlookContact.Value = contact == null ? string.Empty : contact.DisplayName;

                if (ModelState.IsValid)
                {
                    try
                    {
                        KontaktRepository.AddUpdateItem(viewModel.Kontakt);
                        this.ViewBag.SaveStatus = SaveStatus.OK;
                        this.ViewBag.Controller = this.RouteData.Values["controller"];
                        Refresh();
                    }
                    catch (Exception ex)
                    {
                        logger.Error(ex);
                        this.ViewBag.SaveStatus = SaveStatus.Exception;
                    }
                }
                else
                {
                    this.ViewBag.SaveStatus = SaveStatus.ValidationError;
                }

                return PartialView("EditPartial", viewModel);
            }
        }

        [SharePointContextFilter]
        public async Task<ActionResult> Edit(KontaktViewModel viewModel, int id)
        {
            using (Context)
            {
                Kontakt kontaktEntity = KontaktRepository.GetEntityById(id);
                viewModel = new KontaktViewModel(this.HttpContext, Context, kontaktEntity, FormMode.Edit);
                await viewModel.Init();
            }
            return View(viewModel);
        }

        [SharePointContextFilter]
        [HttpPost]
        public async Task<ActionResult> Edit(KontaktViewModel viewModel, FormCollection collection)
        {
            using (Context)
            {
                viewModel =
                    new KontaktViewModel(this.HttpContext, Context, viewModel.Kontakt, FormMode.Edit);
                await viewModel.Init(this.HttpContext);

                Beta.OrgContact contact = viewModel.KontaktyOrganizacji.FirstOrDefault(x => x.Id == viewModel.Kontakt.OutlookContact.Id);
                viewModel.Kontakt.OutlookContact.Value = contact == null ? string.Empty : contact.DisplayName;

                if (ModelState.IsValid)
                {
                    try
                    { 
                        KontaktRepository.AddUpdateItem(viewModel.Kontakt);
                        this.ViewBag.SaveStatus = SaveStatus.OK;
                        this.ViewBag.Controller = this.RouteData.Values["controller"];
                        Refresh();
                    }
                    catch (Exception ex)
                    {
                        logger.Error(ex);
                        this.ViewBag.SaveStatus = SaveStatus.Exception;
                    }
                }
                else
                {
                    this.ViewBag.SaveStatus = SaveStatus.ValidationError;
                }
                return PartialView("EditPartial", viewModel);
            }
        }

        [SharePointContextFilter]
        [HttpPost]
        public async Task<JsonResult> GetOutLookContact(string outlookContactID)
        {
            Beta.OrgContact returnValue = null;
            using (Context)
            {
                KontaktViewModel viewModel = new KontaktViewModel(this.HttpContext, Context);
                await viewModel.Init(this.HttpContext);
                returnValue = viewModel.KontaktyOrganizacji.FirstOrDefault(x => x.Id == outlookContactID);
            }
            return Json(returnValue, JsonRequestBehavior.AllowGet);
        }

        [SharePointContextFilter]
        [HttpGet]
        public JsonResult GetDokumentyFinansoweForKontaktId(int kontaktId)
        {
            IEnumerable<DokumentFinansowy> returnList = new List<DokumentFinansowy>();

            using (Context)
            {
                returnList = DokumentyFinansoweRepository.GetEntityList(listName: GlobalNames.Lists.KontaktyDokumentyFinansowe);
            }

            var returnObject = new { records = returnList.ToList(), total = returnList.Count() };

            return Json(returnObject, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetFile(int id)
        {
            byte[] contents = null;
            Kontakt entity = null;

            using (Context)
            {
                WordDocumentCreator wrodCreator = new WordDocumentCreator(Context);
                entity = KontaktRepository.GetEntityById(id);
                contents = wrodCreator.GetDocumentFromLibrary("/Dokumenty/Kontakt.docx", entity);
            }

            return File(contents, "application/octet-stream", entity.Title + ".docx");
        }
    }
}

Kancelaria365.Web/Controllers/KosztController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using Kancelaria365.Data;
using Kancelaria365.Common;
using NLog;
using System.Threading.Tasks;
using System.Web.Routing;

namespace Kancelaria365.Web.Controllers
{
    public class KosztController :
        BaseSessionGenericController<KosztRepository, Koszt>
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();

        [SharePointContextFilter]
        public ActionResult Index()
        {
            KosztListViewModel viewModel = null;
            using (Context)
            {
                viewModel = new KosztListViewModel(Context);
            }
            return View(viewModel);
        }

        [SharePointContextFilter]
        public ActionResult Details(int id)
        {
            KosztViewModel viewModel = null;
            using (Context)
            {
                Koszt koszt = KosztRepository.GetEntityById(id);
                viewModel = new KosztViewModel(this.HttpContext, Context, koszt, FormMode.Dispaly);
            }
            return View("Edit", viewModel);
        }

        [HttpPost]
        [SharePointContextFilter]
        public ActionResult Create(KosztViewModel viewModel, FormCollection collection)
        {
            using (Context)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        KosztRepository.AddUpdateItem(viewModel.Koszt);
                        this.ViewBag.SaveStatus = SaveStatus.OK;
                        this.ViewBag.Controller = this.RouteData.Values["controller"];
                        Refresh();
                    }
                    catch (Exception ex)
                    {
                        logger.Error(ex);
                        this.ViewBag.SaveStatus = SaveStatus.Exception;
                    }
                }
                else
                {
                    this.ViewBag.SaveStatus = SaveStatus.ValidationError;
                }
                KosztViewModel newViewModel =
                    new KosztViewModel(this.HttpContext, Context, viewModel.Koszt, FormMode.New);
                return PartialView("EditPartial", newViewModel);
            }
        }

        [SharePointContextFilter]
        public ActionResult Create(int? sprawaId)
        {
            KosztViewModel viewModel = null;

            using (Context)
            {
                viewModel = new KosztViewModel(this.HttpContext, Context, sprawaId);
            }
            return View("Edit", viewModel);
        }

        [SharePointContextFilter]
        public ActionResult Edit(KosztViewModel viewModel, int id)
        {
            using (Context)
            {
                Koszt kosztEntity = KosztRepository.GetEntityById(id);
                viewModel = new KosztViewModel(this.HttpContext, Context, kosztEntity, FormMode.Edit);
            }
            return View(viewModel);
        }

        [SharePointContextFilter]
        [HttpPost]
        public ActionResult Edit(KosztViewModel viewModel, FormCollection collection)
        {
            using (Context)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        KosztRepository.AddUpdateItem(viewModel.Koszt);
                        this.ViewBag.SaveStatus = SaveStatus.OK;
                        this.ViewBag.Controller = this.RouteData.Values["controller"];
                        Refresh();
                    }
                    catch (Exception ex)
                    {
                        logger.Error(ex);
                        this.ViewBag.SaveStatus = SaveStatus.Exception;
                    }
                }
                else
                {
                    this.ViewBag.SaveStatus = SaveStatus.ValidationError;
                }
                KosztViewModel newViewModel =
                    new KosztViewModel(this.HttpContext, Context, viewModel.Koszt, FormMode.Edit);
                return PartialView("EditPartial", newViewModel);
            }
        }
    }
}

Kancelaria365.Web/Controllers/SlownikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kancelaria365.Data;
using NLog;

namespace Kancelaria365.Web.Controllers
{
    public class SlownikController : BaseController
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();
        [SharePointContextFilter]
        public ActionResult Index()
        {
            var model = new List<SlownikItem>();

            using (Context)
            {
                if (Context != null)
                {
                    model = SlownikRepository.GetDictionaryItems();
                }
            }

            return View(model);
        }
    }
}

Kancelaria365.Web/Controllers/SprawaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using System.Threading.Tasks;
using Kancelaria365.Data;
using NLog;

namespace Kancelaria365.Web.Controllers
{
    public class SprawaController :
        BaseCacheGenericController<SprawaRepository, Sprawa>
    {
        private new static Logger logger = LogManager.GetCurrentClassLogger();

        [SharePointContextFilter]
        public ActionResult Index()
        {
            SprawaListViewModel model = null;
            using (Context)
            {
                model = new SprawaListViewModel(Context);
            }
            return View(model);
        }

        [SharePointContextFilter]
        public ActionResult Details(int id)
        {
            SprawaViewModel viewModel = null;
            using (Context)
            {
                Sprawa sprawaEntity = SprawaRepository.GetEntityById(id);
                viewModel = new SprawaViewModel(this.HttpContext, Context, sprawaEntity, FormMode.Dispaly);
            }
            return View("Edit", viewModel);
        }

        [SharePointContextFilter]
        public ActionResult Create()
        {
            SprawaViewModel viewModel = null;

            using (Context)
            {
                viewModel = new SprawaViewModel(this.HttpContext,Context);
            }
            return View("Edit", viewModel);
        }

        [SharePointContextFilter]
        [HttpPost]
        public ActionResult Create(SprawaViewModel viewModel, FormCollection collection)
        {
            using (Context)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        SprawaRepository.AddUpdateItem(viewModel.Sprawa);
                        this.ViewBag.SaveStatus = SaveStatus.OK;
                        this.ViewBag.Controller = this.RouteData.Values["controller"];
                        Refresh();
                    }
                    catch (Exception ex)
                    {
                        logger.Error(ex);
                        this.ViewBag.SaveStatus = SaveStatus.Exception;
                    }
                }
                else
                {
                    this.ViewBag.SaveStatus = SaveStatus.ValidationError;
                }
                SprawaViewModel newViewModel =
                    new SprawaViewModel(this.HttpContext, Context, viewModel.Sprawa, FormMode.New);
                return PartialView("EditPartial", newViewModel);
            }
        }

        [SharePointContextFilter]
        public ActionResult Edit(SprawaViewModel viewModel, int id)
        {
            using (Context)
            {
                Sprawa sprawaEntity = SprawaRepository.GetEntityById(id);
                viewModel = new SprawaViewModel(this.HttpContext, Context, sprawaEntity, FormMode.Edit);
            }
            return View(viewModel);
        }

        [SharePointContextFilter]
        [HttpPost]
        public ActionResult Edit(SprawaViewModel viewModel, FormCollection collection)
        {
            using (Context)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        SprawaRepository.AddUpdateItem(viewModel.Sprawa);
                        this.ViewBag.SaveStatus = SaveStatus.OK;
                        this.ViewBag.Controller = this.RouteData.Values["controller"];
                        Refresh();
                    }
                    catch (Exception ex)
                    {
                        logger.Error(ex);
                        this.ViewBag.SaveStatus = SaveStatus.Exception;
                    }
                }
                else
                {
                    this.ViewBag.SaveStatus = SaveStatus.ValidationError;
                }
                SprawaViewModel newViewModel =
                    new SprawaViewModel(this.HttpContext, Context, viewModel.Sprawa, FormMode.Edit);
                return PartialView("EditPartial", newViewModel);
            }
        }
    }
}

Kancelaria365.Web/Views/Shared/Index.cshtml
@model Kancelaria365.Web.HomeListViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row tile_count">
    <div class="animated flipInY col-md-3 col-sm-6 col-xs-6 tile_stats_count">
        <div class="left"></div>
        <div class="right">
            <span class="count_top"><i class="fa fa-users"></i> Liczba klientów</span>
            <div class="count">@Html.Action("GetTotalClientsCount", "Base")</div>
            <span class="count_bottom"><i class="green"></i></span>
        </div>
    </div>
    <div class="animated flipInY col-md-3 col-sm-6 col-xs-6 tile_stats_count">
        <div class="left"></div>
        <div class="right">
            <span class="count_top"><i class="fa fa-cogs"></i> Liczba spraw</span>
            <div class="count">@Html.Action("GetTotalCasesCount", "Base")</div>
            <span class="count_bottom"><i class="green"></i></span>
        </div>
    </div>
    <div class="animated flipInY col-md-3 col-sm-6 col-xs-6 tile_stats_count">
        <div class="left"></div>
        <div class="right">
            <span class="count_top"><i class="fa fa-money"></i> Suma kosztów</span>
            <div class="count">@Html.Action("GetSumaKosztow", "Base")</div>
            <span class="count_bottom"><i class="green"></i></span>
        </div>
    </div>
    <div class="animated flipInY col-md-3 col-sm-6 col-xs-6 tile_stats_count">
        <div class="left"></div>
        <div class="right">
            <span class="count_top"><i class="fa fa-clock-o"></i> Całkowity czas czynności</span>
            <div class="count">@Html.Action("GetSumaCzasuCzynnosci", "Base")</div>
            <span class="count_bottom"><i class="green"></i></span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel tile fixed_height_320">
            <div class="x_title">
                <h2>Czynności przypisane do mnie</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @Html.Partial("CustomGrid", Model.CzynnosciGridViewModel)
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel tile fixed_height_320 overflow_hidden">
            <div class="x_title">
                <h2>Koszty przypisane do mnie</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @Html.Partial("CustomGrid", Model.KosztyGridViewModel)
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        // Pie chart
        //Chart.defaults.global.legend = {
        //    enabled: false
        //};

        //var data = {
        //    labels: [
        //      "Symbian",
        //      "Blackberry",
        //      "Other",
        //      "Android",
        //      "IOS"
        //    ],
        //    datasets: [{
        //        data: [15, 20, 30, 10, 30],
        //        backgroundColor: [
        //          "#BDC3C7",
        //          "#9B59B6",
        //          "#455C73",
        //          "#26B99A",
        //          "#3498DB"
        //        ],
        //        hoverBackgroundColor: [
        //          "#CFD4D8",
        //          "#B370CF",
        //          "#34495E",
        //          "#36CAAB",
        //          "#49A9EA"
        //        ]

        //    }]
        //};

        //var canvasDoughnut = new Chart(document.getElementById("canvas1"), {
        //    type: 'doughnut',
        //    tooltipFillColor: "rgba(51, 51, 51, 0.55)",
        //    data: data
        //});
    });

</script>

Kancelaria365.Web/Views/Shared/View.cshtml
@model IEnumerable<Kancelaria365.Data.GrupaSpraw>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdKontaktu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NazwaKontaktu)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdKontaktu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NazwaKontaktu)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

</table>

Kancelaria365.Web/Views/Shared/_Layout.cshtml
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="~/weight.ico" />

    <title>Kancelaria 365</title>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/gentelella_top")
    @Scripts.Render("~/bundles/custom")
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    @Styles.Render("~/bundles/gentelella")

    @RenderSection("scripts", required: false)

    <script type="text/javascript">

        function ActionToController(controller, params) {
            var items = $("Form").attr("action").split("?");
            var query = items[1];
            var vars = query.split('&');

            var spHostUrl = "";
            for (var i = 0; i < vars.length; i++) {
                var pair = vars[i].split('=');
                if (decodeURIComponent(pair[0]) == "SPHostUrl") {
                    spHostUrl = decodeURIComponent(pair[1]);
                }
            }

            var queryString = items[1];
            var action = "";
            if (params != null && params.length > 0) {
                action = controller + "?SPHostUrl=" + spHostUrl + "&" + params;
            }
            else {
                action = controller + "?SPHostUrl=" + spHostUrl;
            }

            $("Form").attr("action", action);
        }

        function getQueryStringParameter(paramToRetrieve) {
            try {
                var params =
                    document.URL.split("?")[1].split("&");
                var strParams = "";
                for (var i = 0; i < params.length; i = i + 1) {
                    var singleParam = params[i].split("=");
                    if (singleParam[0] == paramToRetrieve)
                        return singleParam[1];
                }
            }
            catch (e) {
                Logger.logError(e);
            }
        }

        function OnBegin() {
            GuiHelper.ajaxIndicatorStart("", "main-body");
            Logger.logInfo("OnBegin");
        }

        function OnFailure() {
            Logger.logInfo("OnFailure");
        }

        function OnComplete() {
            GuiHelper.ajaxIndicatorStop("main-body");

            Logger.logInfo("OnComplete");
        }

        function OnSuccess() {
            Logger.logInfo("OnSuccess");
        }
    </script>
</head>

<body id="main-body" class="nav-md pace-done">
    <div class="pace  pace-inactive">
        <div class="pace-progress" data-progress-text="100%" data-progress="99" style="transform: translate3d(100%, 0px, 0px);">
            <div class="pace-progress-inner"></div>
        </div>
        <div class="pace-activity"></div>
    </div>

    <div class="container body">


        <div class="main_container">

            <div class="col-md-3 left_col">
                <div class="left_col scroll-view" tabindex="5000" style="overflow: hidden; outline: none; cursor: -webkit-grab;">

                    <div class="navbar nav_title" style="border: 0;">
                        <a  href="@Url.Action("Index", "Home")" class="site_title AddSPHostUrl"><i class="fa fa-balance-scale"></i> <span>Kancelaria 365</span></a>
                    </div>
                    <div class="clearfix"></div>

                    <!-- menu prile quick info -->
                    <div class="profile">
                        <div class="profile_pic">
                            <img src="@Url.Action("GetCurrentUserPhoto", "Base")" alt="..." class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Witaj,</span>
                            <h2>@Html.Action("GetCurrentUserDisplayName", "Base")</h2>
                        </div>
                    </div>
                    <!-- /menu prile quick info -->

                    <br>

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

                        <div class="menu_section">
                            <h3>Moduły</h3>
                            <ul class="nav side-menu">
                                <li class="active">
                                    <a class="AddSPHostUrl" href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i>Panel użytkownika<span class="fa"></span></a>
                                </li>
                                <li>
                                    <a class="AddSPHostUrl" href="@Url.Action("Index", "Kalendarz")"><i class="fa fa-calendar"></i>Kalendarz<span class="fa"></span></a>
                                </li>
                                <li>
                                    <a><i class="fa fa-users"></i> Kontakty <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none;">
                                        <li>@Html.ActionLink("Lista kontaktów", "Index", "Kontakt", null, htmlAttributes: new Dictionary<string, object> { { "class", "AddSPHostUrl" } })</li>
                                        <li>@Html.ActionLink("Nowy kontakt", "Create", "Kontakt", null, htmlAttributes: new Dictionary<string, object> { { "class", "AddSPHostUrl" } })</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-cogs"></i> Sprawy <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none;">
                                        <li>@Html.ActionLink("Lista spraw", "Index", "Sprawa", null, htmlAttributes: new Dictionary<string, object> { { "class", "AddSPHostUrl" } })</li>
                                        <li>@Html.ActionLink("Nowa sprawa", "Create", "Sprawa", null, htmlAttributes: new Dictionary<string, object> { { "class", "AddSPHostUrl" } })</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-cog"></i> Czynności <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none;">
                                        <li>@Html.ActionLink("Lista czynności", "Index", "Czynnosc", null, htmlAttributes: new Dictionary<string, object> { { "class", "AddSPHostUrl" } })</li>
                                        <li>@Html.ActionLink("Nowa czynność", "Create", "Czynnosc", null, htmlAttributes: new Dictionary<string, object> { { "class", "AddSPHostUrl" } })</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-money"></i> Koszty <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none;">
                                        <li>@Html.ActionLink("Lista kosztów", "Index", "Koszt", null, htmlAttributes: new Dictionary<string, object> { { "class", "AddSPHostUrl" } })</li>
                                        <li>@Html.ActionLink("Nowy koszt", "Create", "Koszt", null, htmlAttributes: new Dictionary<string, object> { { "class", "AddSPHostUrl" } })</li>
                                    </ul>
                                </li>
                                <li>
                                    <a class="AddSPHostUrl" href="@Url.Action("Index", "Slownik")"><i class="fa fa-book"></i>Słowniki<span class="fa"></span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /sidebar menu -->
                    <!-- /menu footer buttons -->
                    <!-- /menu footer buttons -->
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">

                <div class="nav_menu">
                    <nav class="" role="navigation">
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" aria-expanded="false">
                                    <img src="@Url.Action("GetCurrentUserPhoto", "Base")" alt="">@Html.Action("GetCurrentUserDisplayName", "Base")
                                </a>
                            </li>

                            <li role="presentation" class="dropdown">
                                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-envelope-o"></i>
                                    <span id="messages-count" class="badge bg-green">6</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>

            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main" style="min-height: 564px;">

                @RenderBody()

            </div>
            <!-- /page content -->
        </div>

    </div>
    <script type="text/javascript">
        $("#messages-count").text(GraphHelper.UnreadMessagesCount());
    </script>
    @Scripts.Render("~/bundles/spcontext")
    @Scripts.Render("~/bundles/gentelella_bottom")
</body>

</html>