Kancelaria365.Web/Controllers/CzynnoscController.cs
using Kancelaria365.Common;
using Kancelaria365.Data;
using Kancelaria365.Web.Helpers;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kancelaria365.Web.Controllers
{
    public class CzynnoscController :
        BaseSessionGenericController<CzynnoscRepository, Czynnosc>
    {
        private new static Logger logger = LogManager.GetCurrentClassLogger();

        [SharePointContextFilter]
        public ActionResult Index()
        {
            CzynnoscListViewModel viewModel = null;
            using (Context)
            {
                viewModel = new CzynnoscListViewModel(Context);
            }
            return View(viewModel);
        }

        [SharePointContextFilter]
        public ActionResult Details(int id)
        {
            CzynnoscViewModel viewModel = null;
            using (Context)
            {
                Czynnosc czynnoscEntity = CzynnoscRepository.GetEntityById(id);
                viewModel = new CzynnoscViewModel(this.HttpContext, Context, czynnoscEntity, FormMode.Dispaly);
            }
            return View("Edit", viewModel);
        }

        [SharePointContextFilter]
        public ActionResult Create(int? sprawaId)
        {
            CzynnoscViewModel viewModel = null;

            using (Context)
            {
                viewModel = new CzynnoscViewModel(this.HttpContext, Context, sprawaId);
            }
            return View("Edit", viewModel);
        }

        [HttpPost]
        [SharePointContextFilter]
        public ActionResult Create(CzynnoscViewModel viewModel, FormCollection collection)
        {
            using (Context)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        CzynnoscRepository.AddUpdateItem(viewModel.Czynnosc);
                        this.ViewBag.SaveStatus = SaveStatus.OK;
                        this.ViewBag.Controller = this.RouteData.Values["controller"];
                        Refresh();
                    }
                    catch (Exception ex)
                    {
                        logger.Error(ex);
                        this.ViewBag.SaveStatus = SaveStatus.Exception;
                    }
                }
                else
                {
                    this.ViewBag.SaveStatus = SaveStatus.ValidationError;
                }
                CzynnoscViewModel newViewModel =
                    new CzynnoscViewModel(this.HttpContext, Context, viewModel.Czynnosc, FormMode.New);
                return PartialView("EditPartial", newViewModel);
            }
        }

        [SharePointContextFilter]
        [HttpPost]
        public ActionResult Edit(CzynnoscViewModel viewModel, FormCollection collection)
        {
            using (Context)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        CzynnoscRepository.AddUpdateItem(viewModel.Czynnosc);
                        this.ViewBag.SaveStatus = SaveStatus.OK;
                        this.ViewBag.Controller = this.RouteData.Values["controller"];
                        Refresh();
                    }
                    catch (Exception ex)
                    {
                        logger.Error(ex);
                        this.ViewBag.SaveStatus = SaveStatus.Exception;
                    }
                }
                else
                {
                    this.ViewBag.SaveStatus = SaveStatus.ValidationError;
                }
                CzynnoscViewModel newViewModel =
                    new CzynnoscViewModel(this.HttpContext, Context, viewModel.Czynnosc, FormMode.Edit);
                return PartialView("EditPartial", newViewModel);
            }
        }

        [SharePointContextFilter]
        public ActionResult Edit(CzynnoscViewModel viewModel, int id)
        {
            using (Context)
            {
                Czynnosc czynnosctEntity = CzynnoscRepository.GetEntityById(id);
                viewModel = new CzynnoscViewModel(this.HttpContext, Context, czynnosctEntity, FormMode.Edit);
            }
            return View(viewModel);
        }
    }
}

Kancelaria365.Web/Views/Shared/_Grids/CzynnosciGridFilterView.cshtml
@model Kancelaria365.Web.CzynnoscListViewModel
@{ 
    string token = DateTime.Now.Millisecond.ToString();
}
<div class="search-buttons-panel">
    <div class="form-group">
        <div class="col-md-5">
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.FilterViewModel.Kontakty,
                htmlAttributes: new { @class = "control-label col-md-12" })
        </div>
        <div class="col-md-2">
            @Html.DropDownListFor(m => m.FilterViewModel.Kontakty,
                new SelectList(Model.FilterViewModel.Kontakty, "Id", "Value"),
                htmlAttributes: new { @class = "form-control col-md-12 input-sm" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.FilterViewModel.Sprawy,
                htmlAttributes: new { @class = "control-label col-md-12" })
        </div>
        <div class="col-md-2">
            @Html.DropDownListFor(m => m.FilterViewModel.Sprawy,
                new SelectList(Model.FilterViewModel.Sprawy, "Id", "Value"),
                htmlAttributes: new { @class = "form-control col-md-12 input-sm" })
        </div>
        <div class="col-md-1">
            <button id="btnSimpleSearch" type="button" class="btn btn-info">Szukaj</button>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/spcontext")
<script type="text/javascript">
    var lastKontaktId_@token = -1;
    var lastSprawaId_@token = -1;
    function btnSimpleSearchGetSelectedValues() {
        var kontaktyVal = $("#@Html.IdFor(model => model.FilterViewModel.Kontakty)").val();
        var sprawyVal = $("#@Html.IdFor(model => model.FilterViewModel.Sprawy)").val();
        var clearDataSource = false;
        if (lastKontaktId_@token != kontaktyVal ||
            lastSprawaId_@token != sprawyVal)
        {
            clearDataSource = true;
            lastKontaktId_@token = kontaktyVal;
            lastSprawaId_@token = sprawyVal;
        }
        kontaktyVal = kontaktyVal == 0 ? "" : kontaktyVal;
        sprawyVal = sprawyVal == 0 ? "" : sprawyVal;
        return {
            "Kontakt.Id": kontaktyVal,
            "Sprawa.Id": sprawyVal,
            "ClearDataSource": clearDataSource
        };
    }

    function czynnosciFiltersGetKontaktId() {
        var firma = $("#@Html.IdFor(model => model.FilterViewModel.Kontakty)");
        return firma.val();
    }

    function czynnosciFiltersGetSprawaId() {
        var sprawa = $("#@Html.IdFor(model => model.FilterViewModel.Sprawy)");
        return sprawa.val();
    }

    CascadeKontaktSprawaDropDowns.init(
        "@Html.IdFor(model => model.FilterViewModel.Kontakty)", 
        "@Html.IdFor(model => model.FilterViewModel.Sprawy)", 
        "@Url.Action("GetKontakt", "Czynnosc")",
        "@Url.Action("GetSprawy", "Czynnosc")");
</script>

Kancelaria365.Web/Views/Shared/_Grids/CzynnosciGridView.cshtml
@model Kancelaria365.Web.CzynnoscListViewModel


@Html.Partial("CustomGrid", Model.GridViewModel)

<script type="text/javascript">
    $("#btnSearch").on("click", function () {
        reloadSprawy();
    });

    function simpleSearch() {
        sprawy_grid.reload({
            @*statusText: $("#@Html.IdFor(model => model.FilterViewModel.Stany) option:selected").text(),
            kategoriaId: $("#@Html.IdFor(model => model.FilterViewModel.Kategorie)").val(),*@
        });
    }

    function advancedSearch() {
    }

    $("#createNewCzynnosc").on("click", function () {
        var kontaktId = czynnosciFiltersGetKontaktId();
        var sprawaId = czynnosciFiltersGetSprawaId();
        this.href = this.href + "?kontaktId=" + kontaktId + "&sprawaId=" + sprawaId;
    });

</script>

Kancelaria365.Web/Views/Shared/_Grids/KontaktyGridFilterView.cshtml
@model Kancelaria365.Web.KontaktListViewModel


<div class="search-buttons-panel">
    <div class="form-group">
        <div class="col-md-5">
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.FilterViewModel.Statusy,
                htmlAttributes: new { @class = "control-label col-md-12" })
        </div>
        <div class="col-md-2">
            @Html.DropDownListFor(m => m.FilterViewModel.Statusy,
                new SelectList(Model.FilterViewModel.Statusy),
                htmlAttributes: new { @class = "form-control col-md-12 input-sm" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.FilterViewModel.Kategorie,
                htmlAttributes: new { @class = "control-label col-md-12" })
        </div>
        <div class="col-md-2">
            @Html.DropDownListFor(m => m.FilterViewModel.Kategorie,
                new SelectList(Model.FilterViewModel.Kategorie, "Id", "Value"),
                htmlAttributes: new { @class = "form-control col-md-12 input-sm" })
        </div>
        <div class="col-md-1">
            <button id="btnSimpleSearch" type="button" class="btn btn-info">Szukaj</button>
        </div>
    </div>
</div>

<script type="text/javascript">
    function btnSimpleSearchGetSelectedValues() {
        var statusyVal = $("#@Html.IdFor(model => model.FilterViewModel.Statusy)").val();
        var kategoriaVal = $("#@Html.IdFor(model => model.FilterViewModel.Kategorie)").find(":selected").text();
        statusyVal = statusyVal == "--" ? "" : statusyVal;
        kategoriaVal = kategoriaVal == "--" ? "" : kategoriaVal;
        return {
            "Status": statusyVal,
            "Kategoria.Value": kategoriaVal
        };
    }
</script>

Kancelaria365.Web/Views/Shared/_Grids/KontaktyGridView.cshtml
@model Kancelaria365.Web.KontaktListViewModel


@Html.Partial("CustomGrid", Model.GridViewModel)

<script type="text/javascript">
    $("#btnSearch").on("click", function () {
        reloadKontakty();
    });

    function simpleSearch() {
        kontakty_grid.reload({
            statusText: $("#@Html.IdFor(model => model.FilterViewModel.Statusy) option:selected").text(),
            kategoriaId: $("#@Html.IdFor(model => model.FilterViewModel.Kategorie)").val(),
        });
    }

    function advancedSearch() {
        kontakty_grid.reload({
            statusText: "Kontakt",
            sprawy: true,
            konta: true,
            zadania: true,
            czynnosci: true,
            koszty: true,
            kontakty: true,
        });
    }

</script>

Kancelaria365.Web/Views/Shared/_Grids/KosztyGridFilterView.cshtml
@model Kancelaria365.Web.KosztListViewModel
@{ 
    string token = DateTime.Now.Millisecond.ToString();
}
<div class="search-buttons-panel">
    <div class="form-group">
        <div class="col-md-5">
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.FilterViewModel.Kontakty,
                htmlAttributes: new { @class = "control-label col-md-12" })
        </div>
        <div class="col-md-2">
            @Html.DropDownListFor(m => m.FilterViewModel.Kontakty,
                new SelectList(Model.FilterViewModel.Kontakty, "Id", "Value"),
                htmlAttributes: new { @class = "form-control col-md-12 input-sm" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.FilterViewModel.Sprawy,
                htmlAttributes: new { @class = "control-label col-md-12" })
        </div>
        <div class="col-md-2">
            @Html.DropDownListFor(m => m.FilterViewModel.Sprawy,
                new SelectList(Model.FilterViewModel.Sprawy, "Id", "Value"),
                htmlAttributes: new { @class = "form-control col-md-12 input-sm" })
        </div>
        <div class="col-md-1">
            <button id="btnSimpleSearch" type="button" class="btn btn-info">Szukaj</button>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/spcontext")
<script type="text/javascript">
    var lastKontaktId_@token = -1;
    var lastSprawaId_@token = -1;
    function btnSimpleSearchGetSelectedValues() {
        var kontaktyVal = $("#@Html.IdFor(model => model.FilterViewModel.Kontakty)").val();
        var sprawyVal = $("#@Html.IdFor(model => model.FilterViewModel.Sprawy)").val();
        var clearDataSource = false;
        if (lastKontaktId_@token != kontaktyVal ||
            lastSprawaId_@token != sprawyVal)
        {
            clearDataSource = true;
            lastKontaktId_@token = kontaktyVal;
            lastSprawaId_@token = sprawyVal;
        }
        kontaktyVal = kontaktyVal == 0 ? "" : kontaktyVal;
        sprawyVal = sprawyVal == 0 ? "" : sprawyVal;
        return {
            "Kontakt.Id": kontaktyVal,
            "Sprawa.Id": sprawyVal,
            "ClearDataSource": clearDataSource
        };
    }

    function kosztyFiltersGetKontaktId() {
        var firma = $("#@Html.IdFor(model => model.FilterViewModel.Kontakty)");
        return firma.val();
    }

    function kosztyFiltersGetSprawaId() {
        var sprawa = $("#@Html.IdFor(model => model.FilterViewModel.Sprawy)");
        return sprawa.val();
    }

    CascadeKontaktSprawaDropDowns.init(
        "@Html.IdFor(model => model.FilterViewModel.Kontakty)",
        "@Html.IdFor(model => model.FilterViewModel.Sprawy)",
        "@Url.Action("GetKontakt", "Czynnosc")",
        "@Url.Action("GetSprawy", "Czynnosc")");
</script>

Kancelaria365.Web/Views/Shared/_Grids/KosztyGridView.cshtml
@model Kancelaria365.Web.KosztListViewModel


@Html.Partial("CustomGrid", Model.GridViewModel)

<script type="text/javascript">
    $("#btnSearch").on("click", function () {
        //reloadSprawy();
    });

    function simpleSearch() {
        sprawy_grid.reload({
        });
    }

    function advancedSearch() {
    }

    $("#createNewKoszt").on("click", function () {
        var kontaktId = kosztyFiltersGetKontaktId();
        var sprawaId = kosztyFiltersGetSprawaId();
        this.href = this.href + "?kontaktId=" + kontaktId + "&sprawaId=" + sprawaId;
    });

</script>

Kancelaria365.Web/Views/Shared/_Grids/SprawyGridFilterView.cshtml
@model Kancelaria365.Web.SprawaListViewModel

<div class="search-buttons-panel">
    <div class="form-group">
        <div class="col-md-5">
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.FilterViewModel.Stany,
                htmlAttributes: new { @class = "control-label col-md-12" })
        </div>
        <div class="col-md-2">
            @Html.DropDownListFor(m => m.FilterViewModel.Stany,
                new SelectList(Model.FilterViewModel.Stany),
                htmlAttributes: new { @class = "form-control col-md-12 input-sm" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.FilterViewModel.Kategorie,
                htmlAttributes: new { @class = "control-label col-md-12" })
        </div>
        <div class="col-md-2">
            @Html.DropDownListFor(m => m.FilterViewModel.Kategorie,
                new SelectList(Model.FilterViewModel.Kategorie, "Id", "Value"),
                htmlAttributes: new { @class = "form-control col-md-12 input-sm" })
        </div>
        <div class="col-md-1">
            <button id="btnSimpleSearch" type="button" class="btn btn-info">Szukaj</button>
        </div>
    </div>
</div>

<script type="text/javascript">
    function btnSimpleSearchGetSelectedValues() {
        var stanVal = $("#@Html.IdFor(model => model.FilterViewModel.Stany)").val();
        var kategoriaVal = $("#@Html.IdFor(model => model.FilterViewModel.Kategorie)").val();
        stanVal = stanVal == "--" ? "" : stanVal;
        kategoriaVal = kategoriaVal == 0 ? "" : kategoriaVal;
        return {
            "Stan": stanVal,
            "Kategoria": kategoriaVal
        };
    }
</script>

Kancelaria365.Web/Views/Shared/_Grids/SprawyGridView.cshtml
@model Kancelaria365.Web.SprawaListViewModel

@Html.Partial("CustomGrid", Model.GridViewModel)

<script type="text/javascript">
    $("#btnSearch").on("click", function () {
        reloadSprawy();
    });

    function simpleSearch() {
        sprawy_grid.reload({
            statusText: $("#@Html.IdFor(model => model.FilterViewModel.Stany) option:selected").text(),
            kategoriaId: $("#@Html.IdFor(model => model.FilterViewModel.Kategorie)").val(),
        });
    }

    function advancedSearch() {
        sprawy_grid.reload({
            statusText: "Kontakt",
            sprawy: true,
            konta: true,
            zadania: true,
            czynnosci: true,
            koszty: true,
            kontakty: true,
        });
    }

</script>

Kancelaria365.Web/Views/Shared/_Grids/ZadaniaGridFilterView.cshtml
@model Kancelaria365.Web.ZadanieListViewModel

@{
    string dateFormatString = GlobalNames.FormatStrings.DateFormatString;
}


<div class="search-buttons-panel">
    <div class="form-group">
        <div class="col-md-5">
        </div>
        <div class="col-md-2">
            @Html.LabelFor(model => model.FilterViewModel.PrzypisaneDoMnie,
                htmlAttributes: new { @class = "control-label col-md-12" })
        </div>
        <div class="col-md-1">
            @Html.CheckBoxFor(model => model.FilterViewModel.PrzypisaneDoMnie,
                htmlAttributes: new { @class = "bs-checkbox-input" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.FilterViewModel.ZDnia,
                htmlAttributes: new { @class = "control-label col-md-12" })
        </div>
        <div class="col-md-2">
            @Html.TextBoxFor(model => model.FilterViewModel.ZDnia, dateFormatString,
                htmlAttributes: new { @class = "form-control col-sm-12" })
        </div>
        <div class="col-md-1">
            <button id="btnSimpleSearch" type="button" class="btn btn-info">Szukaj</button>
        </div>
    </div>
</div>

<script type="text/javascript">
    function btnSimpleSearchGetSelectedValues() {
        var przypisaneDoMnieVal = $("#@Html.IdFor(model => model.FilterViewModel.PrzypisaneDoMnie)").val();
        var zDniaVal = $("#@Html.IdFor(model => model.FilterViewModel.ZDnia)").val();
        return {
            "PrzypisaneDoMnie": przypisaneDoMnieVal,
            "ZDnia": zDniaVal
        };
    }

    DateTimeHelper.createDatePicker("@Html.IdFor(model => model.FilterViewModel.ZDnia)");
</script>

Kancelaria365.Web/Views/Shared/_Grids/ZadaniaGridView.cshtml
@model Kancelaria365.Web.ZadanieListViewModel


<div class="add-new-buttons-panel">
    <div class="form-group">
        <div class="col-md-12">
            @Html.ActionLink("Nowe zadanie", "Create", new { controller = "Zadanie" }, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>
<br />
@Html.Partial("CustomGrid", Model.ZadaniaGridViewModel)

<script type="text/javascript">
    @*$("#btnSearch").on("click", function () {
        reloadKontakty();
    });

    function simpleSearch() {
        kontakty_grid.reload({
            statusText: $("#@Html.IdFor(model => model.FilterViewModel.Statusy) option:selected").text(),
            kategoriaId: $("#@Html.IdFor(model => model.FilterViewModel.Kategorie)").val(),
        });
    }*@

    //function advancedSearch() {
    //    kontakty_grid.reload({
    //        statusText: "Kontakt",
    //        sprawy: true,
    //        konta: true,
    //        zadania: true,
    //        czynnosci: true,
    //        koszty: true,
    //        kontakty: true,
    //    });
    //}

</script>